# Site settings
title: DATOS.GOB.MX
email: hola@datos.gob.mx
description: >
  En datos.gob.mx puedes descargar y utilizar libremente datos abiertos
  que el Gobierno de la República genera y recolecta.
baseurl: ""
url: "http://datos.gob.mx/"
twitter_username: DatosGobMx
twitter_text: "Descarga y utiliza libremente datos abiertos que el Gobierno de la República genera y recolecta. @GobRep @DatosGobMx"
github_username:  mxabierto

# Lista de Colaboradores
collaborators:
  secretaria_salud:
    title: "Secretaria de Salud"
    site: "http://portal.salud.gob.mx/"
    logo_url: "logoSALUD_hoz-233x80.png"
  imco:
    title: "IMCO"
    site: "http://imco.org.mx/home/"
    logo_url: "IMCO_presidencia-205x80.jpg"
  data4:
    title: "Data4"
    site: ""
    logo_url: "D4_Logo-80x80.png"
  inegi_facil:
    title: "INEGI Fácil"
    site: ""
    logo_url: "logo_160-80x80.png"
  cartografica:
    title: "Cartográfica"
    site: "http://cartografica.mx/"
    logo_url: "logo_cartografica-72-57x80.png"
    
# Build settings
markdown: kramdown
gems: ['jekyll-redirect-from']
jekyll_timeago:
  depth: 1 # Level of detail
  today: 'hoy'
  yesterday: 'ayer'
  tomorrow: 'mañana'
  and: 'y'
  suffix: ''
  prefix: 'hace'
  suffix_future: 'en'
  prefix_future: ''
  years: 'años'
  year: 'año'
  months: 'meses'
  month: 'mes'
  weeks: 'semanas'
  week: 'semana'
  days: 'dias'
  day: 'dia'
